name: exp
channels:
  - defaults
  - conda-forge
dependencies:
  - python =3.8.*
  - pytest
  - scikit-learn
  - scikit-optimize
  - pandas
  - matplotlib
  - jupyter
  - requests
  - pip
  - pip:
      - tensorflow
      - ta
