name: exp
channels:
  - defaults
#  - conda-forge
#  - Quantopian
dependencies:
  - python =3.7.*
  - pytest
  #  - zipline  # Currently (1.3.0) needs manual edits to zipline/data/benchmarks.py so that it includes the fix here: https://github.com/quantopian/zipline/issues/2480
  - tensorflow =2.0.0
  - scikit-learn
  - pyaml # scikit-optimize # Current version (0.6) is not available from conda or pip, so I clone the git instead, so need to manually add pyaml dependency.
  - pandas
  - matplotlib
  - jupyter
  - requests
  - pip:
      - ta
