name: exp
channels:
  - defaults
#  - conda-forge
#  - Quantopian
dependencies:
  - python =3.7.*
#  - zipline  # Currently (1.3.0) needs manual edits to zipline/data/benchmarks.py so that it includes the fix here: https://github.com/quantopian/zipline/issues/2480
  - tensorflow =2.0.0
  - scikit-learn
  - scikit-optimize
  - pandas
  - matplotlib
  - jupyter
  - requests
  - pip:
      - ta
